/**
 * Generated by: npm run sup (scripts/sync-supabase-config.mjs)
 * Do not edit by hand; change .env and re-run npm run sup
 */
window.SONGSHARE_SUPABASE = {
  "url": "https://wxcuipdfrohozowdhlql.supabase.co",
  "anonKey": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4Y3VpcGRmcm9ob3pvd2RobHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMDkzOTUsImV4cCI6MjA5MTU4NTM5NX0.i69DiFcUlrxDQjt3xuZc5KVDCNo3ysf_jemjw9Uzt1w"
};

(function () {
  var c = window.SONGSHARE_SUPABASE || {};
  var k = String(c.anonKey || "").trim();
  var k2 = String(window.SONGSHARE_SUPABASE_ANON_KEY || "").trim();
  if (c.url && !k && !k2 && typeof console !== "undefined" && console.warn) {
    console.warn(
      "[Noteion] Add your Supabase anon public key — run npm run sup after setting .env"
    );
  }
  if ((k || k2).indexOf("http") === 0 && typeof console !== "undefined" && console.error) {
    console.error("[Noteion] The anon key must be a JWT (eyJ…), not a URL.");
  }
})();
